name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: Install dependencies
        run: yarn
      - name: Test
        run: npm test
